version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
