boundary_acceptance <- function() {
  fails <- function(expr) {
    stopifnot(inherits(
      tryCatch(
        {
          force(expr)
          NULL
        },
        error = identity
      ),
      'error'
    ))
  }
  base <- jsonlite::fromJSON(
    system.file('catalogue/schema.json', package = 'specmill'),
    simplifyVector = FALSE
  )
  file <- tempfile(fileext = '.json')
  read <- function(document) {
    jsonlite::write_json(document, file, auto_unbox = TRUE)
    specmill::read_operations(file)
  }
  cyclic <- base
  cyclic$components$schemas$Item <- list('$ref' = '#/components/schemas/Item')
  stopifnot(any(vapply(
    read(cyclic)$diagnostics,
    function(d) identical(d$code, 'recursive_reference'),
    logical(1)
  )))
  bad <- base
  bad$paths[['/items/{item_id}']]$get$parameters[[
    2
  ]]$name <- 'a "quote" `tick`\nline'
  parsed <- read(bad)
  code <- specmill::render_operation(
    parsed$operations$get_item,
    list(helper = 'request_helper', hooks = list())
  )
  stopifnot(length(parse(text = code)) == 1L)
  # Parse failures are diagnosed; no schema text is executed.
  bad$paths[['/items/{item_id}']]$get$operationId <- 'stop("external code")'
  stopifnot(length(read(bad)$operations) == 4L)
  bad$paths[['/items/{item_id}']]$get$operationId <- 'refresh'
  fails(read(bad))
  original <- read(base)
  duplicated <- base
  duplicated$paths[['/items/{item_id}']]$get$parameters[[2L]]$name <- 'item_id'
  duplicate_op <- read(duplicated)$operations$get_item
  context <- new.env(parent = baseenv())
  context$request_helper <- function(...) list(...)
  eval(
    parse(
      text = specmill::render_operation(
        duplicate_op,
        list(helper = 'request_helper')
      )
    ),
    context
  )
  duplicate_call <- context$get_item(item_id = 'path', item_id.1 = 'query')
  stopifnot(
    duplicate_call$path_params$item_id == 'path',
    duplicate_call$query$item_id == 'query'
  )
  inputs <- specmill::operation_fixtures(original$operations)
  stopifnot(inputs$get_item$language == 'en', inputs$list_items$page == 1L)
  changed <- base
  changed$paths[['/items']]$get$parameters[[2]] <- list(
    name = 'tenant',
    'in' = 'query',
    required = TRUE,
    schema = list(type = 'string', enum = list('reviewed'))
  )
  updated <- specmill::operation_fixtures(read(changed)$operations)
  stopifnot(updated$list_items$tenant == 'reviewed')
  changed$paths[['/items']]$get$parameters[[2]]$schema <- list(
    type = 'string',
    pattern = '^x{12}$'
  )
  fails(specmill::operation_fixtures(read(changed)$operations))
  supplied <- specmill::operation_fixtures(
    read(changed)$operations,
    list(list_items = list(tenant = 'xxxxxxxxxxxx'))
  )
  stopifnot(supplied$list_items$tenant == 'xxxxxxxxxxxx')
  large <- base
  large$paths <- setNames(
    lapply(seq_len(2000L), function(i) {
      list(
        get = list(
          operationId = paste0('item_', i),
          responses = list('200' = list(description = 'ok'))
        )
      )
    }),
    paste0('/item/', seq_len(2000L))
  )
  started <- proc.time()
  result <- read(large)
  elapsed <- proc.time() - started
  stopifnot(length(result$operations) == 2000L, !length(result$diagnostics))
  root <- tempfile('ownership-')
  dir.create(root)
  header <- '# Generated by specmill; do not edit by hand.'
  specmill::apply_files(
    root,
    list('good.R' = paste(header, 'x <- 1', sep = '\n')),
    mode = 'apply'
  )
  before <- tools::md5sum(file.path(root, 'good.R'))
  fails(specmill::apply_files(
    root,
    list('good.R' = paste(header, 'x <- 2', sep = '\n')),
    remove = 'good.R',
    mode = 'apply'
  ))
  stopifnot(identical(before, tools::md5sum(file.path(root, 'good.R'))))
  fails(specmill::apply_files(
    root,
    list('good.R' = paste(header, 'x <- 2', sep = '\n'), 'bad.R' = 'x <- ('),
    mode = 'apply'
  ))
  stopifnot(
    identical(before, tools::md5sum(file.path(root, 'good.R'))),
    !file.exists(file.path(root, 'bad.R'))
  )
  generation_root <- tempfile('interrupted-generation-')
  dir.create(generation_root)
  spec <- list(
    files = system.file('catalogue/schema.json', package = 'specmill'),
    helper = 'request_helper'
  )
  specmill::generate_client(generation_root, spec, 'apply')
  previous <- tools::md5sum(list.files(
    file.path(generation_root, 'R'),
    full.names = TRUE
  ))
  spec$renderer <- function(operation, spec) {
    if (operation$name == 'create_item') {
      stop('Intentional render interruption')
    }
    specmill::render_operation(operation, spec)
  }
  fails(specmill::generate_client(generation_root, spec, 'apply'))
  stopifnot(identical(
    previous,
    tools::md5sum(list.files(
      file.path(generation_root, 'R'),
      full.names = TRUE
    ))
  ))
  fails(specmill::apply_files(
    root,
    list('C:/escape.R' = 'x <- 1'),
    mode = 'apply'
  ))
  writeLines('manual <- TRUE', file.path(root, 'manual.R'))
  result <- specmill::apply_files(
    root,
    list(),
    remove = c('good.R', 'manual.R'),
    mode = 'plan'
  )
  applied <- specmill::apply_files(root, list(), remove = c('good.R', 'manual.R'), mode = 'apply')
  stopifnot(applied[[2L]]$action == 'retained')
  stopifnot(
    !file.exists(file.path(root, 'good.R')),
    file.exists(file.path(root, 'manual.R'))
  )
  cat(
    'Boundaries: cycles, quotes, names, fixture constraints, 2000 operations (',
    elapsed[['elapsed']],
    ' s), parse failure rollback, removal and path containment passed.\n',
    sep = ''
  )
}
if (sys.nframe() == 0L) {
  boundary_acceptance()
}
