formatting_acceptance <- function() {
  if (!nzchar(Sys.which('air'))) {
    cat('Formatting: Air unavailable; formatter acceptance skipped.\n')
    return(invisible(NULL))
  }
  root <- tempfile('formatted-client-')
  dir.create(root)
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  fixture <- system.file('catalogue', package = 'specmill', mustWork = TRUE)
  stopifnot(all(file.copy(
    list.files(fixture, full.names = TRUE),
    root,
    recursive = TRUE
  )))
  version <- sub(
    '^air ',
    '',
    system2(Sys.which('air'), '--version', stdout = TRUE)
  )
  project <- list(
    config_version = 1L,
    services = list('service.yml'),
    formatter = list(name = 'air', version = version)
  )
  yaml::write_yaml(project, file.path(root, 'specmill.yml'))
  # Avoid Air's "Generated by" skip directive: owned output must still format.
  formatted <- getFromNamespace('format_output', 'specmill')(
    root,
    list(
      'tests/testthat/test-contract.R' = '# Generated with specmill; do not edit by hand.\nx<-function(){1+2}'
    ),
    project$formatter
  )
  stopifnot(grepl('x <- function', formatted[[1L]], fixed = TRUE))
  formatted_path <- file.path(root, 'formatted.R')
  writeLines(formatted[[1L]], formatted_path, useBytes = TRUE)
  stopifnot(
    system2(
      Sys.which('air'),
      c('format', '--check', shQuote(formatted_path))
    ) ==
      0L
  )
  unlink(formatted_path)
  writeLines(
    c(
      'id: catalogue',
      'schemas: {files: [schema.json]}',
      'helper: catalogue_request'
    ),
    file.path(root, 'service.yml')
  )
  hashes <- function() {
    tools::md5sum(list.files(
      root,
      recursive = TRUE,
      full.names = TRUE,
      all.files = TRUE
    ))
  }
  before <- hashes()
  specmill::generate_client(validation = FALSE, root, config = 'specmill.yml', mode = 'plan')
  stopifnot(identical(before, hashes()))
  specmill::generate_client(validation = FALSE, root, config = 'specmill.yml', mode = 'apply')
  before <- hashes()
  specmill::generate_client(validation = FALSE, root, config = 'specmill.yml', mode = 'check')
  specmill::generate_client(validation = FALSE, root, config = 'specmill.yml', mode = 'apply')
  stopifnot(
    identical(before, hashes()),
    identical(
      jsonlite::read_json(file.path(root, '.specmill/manifest.json'))$formatter,
      project$formatter
    )
  )
  project$formatter$version <- '0.0.0'
  yaml::write_yaml(project, file.path(root, 'specmill.yml'))
  before <- hashes()
  error <- tryCatch(
    specmill::generate_client(validation = FALSE, root, config = 'specmill.yml', mode = 'apply'),
    error = identity
  )
  stopifnot(
    inherits(error, 'error'),
    grepl('version differs', conditionMessage(error)),
    identical(before, hashes())
  )
  cat(
    'Formatting: pinned Air, isolated formatting, read-only planning and unchanged second apply passed.\n'
  )
}
if (sys.nframe() == 0L) {
  formatting_acceptance()
}
