reconciliation_acceptance <- function() {
  locale_root <- tempfile('locale-manifest-')
  dir.create(locale_root)
  desired_locale <- list(Z.R = 'Z <- 1', a.R = 'a <- 2')
  withr::with_locale(
    c(LC_COLLATE = 'C'),
    specmill::apply_files(locale_root, desired_locale, mode = 'apply')
  )
  locale <- if (.Platform$OS.type == 'windows') {
    'English_United States.utf8'
  } else {
    'en_US.UTF-8'
  }
  locale_plan <- withr::with_locale(
    c(LC_COLLATE = locale),
    specmill::apply_files(locale_root, desired_locale, mode = 'check')
  )
  stopifnot(all(vapply(
    locale_plan,
    function(x) x$action == 'unchanged',
    logical(1)
  )))
  fails <- function(expr, pattern = NULL) {
    error <- tryCatch(
      {
        force(expr)
        NULL
      },
      error = identity
    )
    stopifnot(inherits(error, 'error'))
    if (!is.null(pattern)) stopifnot(grepl(pattern, conditionMessage(error)))
  }
  operation <- function(service, required = FALSE) {
    list(
      service = service,
      key = 'GET /items',
      name = paste0(service, '_items'),
      path = '/items',
      method = 'GET',
      body = NULL,
      body_required = FALSE,
      servers = list(list(url = 'https://api.example.invalid')),
      server_source = 'root',
      parameters = list(list(
        name = 'limit',
        location = 'query',
        required = required,
        schema = list(type = 'integer')
      )),
      response = list()
    )
  }
  before <- list(operations = list(operation('first'), operation('second')))
  after <- list(
    operations = list(operation('first'), operation('second', TRUE))
  )
  delta <- specmill::compare_operations(before, after)
  stopifnot(length(delta) == 1L, delta[[1L]]$key == 'second GET /items')
  server_after <- before
  server_after$operations[[1L]]$servers[[1L]]$url <-
    'https://new.example.invalid'
  server_delta <- specmill::compare_operations(before, server_after)
  stopifnot(
    length(server_delta) == 1L,
    server_delta[[1L]]$status == 'review',
    server_delta[[1L]]$reason == 'Server selection changed'
  )
  op <- operation('sample')
  op$name <- 'request_helper'
  fails(
    specmill::render_operation(op, list(helper = 'request_helper')),
    'collides'
  )
  hooks <- new.env(parent = baseenv())
  hooks$before <- function(state) state
  stopifnot(
    !specmill::validate_hooks(
      list(absent = list(pre_request = 'before')),
      list(),
      hooks
    )$valid
  )
  value <- getFromNamespace('fixture_value', 'specmill')
  stopifnot(is.null(value(
    list(type = 'string', nullable = TRUE, example = 'example'),
    NULL
  )))
  fails(value(list(type = 'string', example = 'example'), NULL), 'not nullable')
  stopifnot(
    identical(value(list(type = 'boolean'), FALSE), FALSE),
    value(list(type = 'integer'), 0) == 0
  )

  root <- tempfile('reconciliation-')
  dir.create(root)
  header <- '# Generated by specmill; do not edit by hand.'
  original <- paste(header, 'example <- function() 1', sep = '\n')
  changed <- paste(header, 'example <- function() 2', sep = '\n')
  writeLines(original, file.path(root, 'legacy.R'))
  entries <- specmill::apply_files(root, list(legacy.R = changed), mode = 'plan')
  stopifnot(entries[[1L]]$action == 'protected')
  fails(
    specmill::apply_files(root, list(legacy.R = changed), mode = 'apply'),
    'Protected'
  )
  stopifnot(!dir.exists(file.path(root, '.specmill')))
  fails(
    specmill::apply_files(
      root,
      list(fresh.R = original),
      mode = 'apply',
      validate = function() {
        stopifnot(dir.exists(file.path(root, '.specmill-lock')))
        stop('Stale input')
      }
    ),
    'Stale input'
  )
  stopifnot(
    !file.exists(file.path(root, 'fresh.R')),
    !dir.exists(file.path(root, '.specmill-lock'))
  )
  specmill::apply_files(root, list(owned.R = original), mode = 'apply')
  writeLines(changed, file.path(root, 'owned.R'))
  stopifnot(
    specmill::apply_files(root, list(owned.R = original), mode = 'plan')[[
      1L
    ]]$action ==
      'protected'
  )
  writeLines(original, file.path(root, 'owned.R'))
  specmill::apply_files(root, list(owned.R = changed), mode = 'apply')
  hashes <- tools::md5sum(list.files(
    root,
    recursive = TRUE,
    all.files = TRUE,
    full.names = TRUE
  ))
  stopifnot(
    specmill::apply_files(root, list(owned.R = changed), mode = 'apply')[[
      1L
    ]]$action ==
      'unchanged'
  )
  stopifnot(identical(
    hashes,
    tools::md5sum(list.files(
      root,
      recursive = TRUE,
      all.files = TRUE,
      full.names = TRUE
    ))
  ))
  fails(
    specmill::apply_files(root, list('A.R' = original, 'a.R' = original)),
    'collide'
  )
  fails(specmill::apply_files(root, list('../escape.R' = original)), 'Unsafe')
  # Metadata-only drift must be visible without changing any project file.
  desired <- list(owned.R = changed)
  attr(desired, 'inputs') <- list('policy.yml' = 'reviewed-input-hash')
  before <- tools::md5sum(names(hashes))
  for (mode in c('plan', 'check')) {
    planned <- specmill::apply_files(root, desired, mode = mode)
    stopifnot(
      planned[[1L]]$action == 'unchanged',
      planned[[2L]]$file == '.specmill/manifest.json',
      planned[[2L]]$action == 'write',
      identical(before, tools::md5sum(names(hashes)))
    )
  }
  specmill::apply_files(root, desired, mode = 'apply')
  stopifnot(length(specmill::apply_files(root, desired, mode = 'check')) == 1L)
  # Shared-file owner arrays survive a later test-only publication unchanged.
  grouped <- list(
    grouped.R = 'first <- function() 1\nsecond <- function() 2',
    test.R = 'test <- TRUE'
  )
  attr(grouped, 'operations') <- list(
    grouped.R = c('service GET /first', 'service GET /second'),
    test.R = 'service GET /first'
  )
  specmill::apply_files(root, grouped, mode = 'apply')
  scoped <- grouped['test.R']
  attr(scoped, 'operations') <- attr(grouped, 'operations')['test.R']
  stopifnot(all(vapply(
    specmill::apply_files(root, scoped, mode = 'check'),
    function(x) x$action == 'unchanged',
    logical(1)
  )))
  journal <- file.path(root, '.specmill-interrupted')
  dir.create(journal)
  saveRDS(list(), file.path(journal, 'recovery.rds'))
  fails(
    specmill::apply_files(root, list(fresh.R = original), mode = 'apply'),
    'recovery'
  )
  stopifnot(length(specmill::recover_client(root)) == 1L)
  specmill::recover_client(root, 'apply')
  stopifnot(!dir.exists(journal))

  # Fail at both outputs and the manifest; verify rollback and recovery.
  for (write in 1:3) {
    fault_root <- tempfile('fault-')
    dir.create(fault_root)
    specmill::apply_files(
      fault_root,
      list(one.R = original, two.R = original),
      mode = 'apply'
    )
    originals <- tools::md5sum(list.files(
      fault_root,
      recursive = TRUE,
      all.files = TRUE,
      full.names = TRUE
    ))
    context <- new.env(parent = asNamespace('specmill'))
    count <- 0L
    context$file.copy <- function(from, to, ...) {
      if (grepl('\\.new$', from)) {
        count <<- count + 1L
        if (count == write) return(FALSE)
      }
      base::file.copy(from, to, ...)
    }
    apply <- specmill::apply_files
    environment(apply) <- context
    fails(
      apply(fault_root, list(one.R = changed, two.R = changed), mode = 'apply'),
      'verify'
    )
    stopifnot(identical(
      unname(originals),
      unname(tools::md5sum(names(originals)))
    ))
    fails(specmill::apply_files(fault_root, list(), mode = 'apply'), 'recovery')
    specmill::recover_client(fault_root, 'apply')
    stopifnot(length(specmill::recover_client(fault_root)) == 0L)
  }
  # Hard termination cannot run on.exit(). Exercise the documented stale-lock path.
  worker <- callr::r_bg(
    function(root, changed) {
      context <- new.env(parent = asNamespace('specmill'))
      context$file.copy <- function(from, to, ...) {
        result <- base::file.copy(from, to, ...)
        if (grepl('\\.new$', from)) {
          writeLines('ready', file.path(root, 'interrupted'))
          Sys.sleep(60)
        }
        result
      }
      apply <- specmill::apply_files
      environment(apply) <- context
      apply(root, list(one.R = changed, two.R = changed), mode = 'apply')
    },
    args = list(fault_root, changed),
    libpath = .libPaths()
  )
  on.exit(if (worker$is_alive()) worker$kill(), add = TRUE)
  deadline <- Sys.time() + 20
  while (
    !file.exists(file.path(fault_root, 'interrupted')) &&
      worker$is_alive() &&
      Sys.time() < deadline
  ) {
    Sys.sleep(0.05)
  }
  stopifnot(file.exists(file.path(fault_root, 'interrupted')))
  worker$kill()
  worker$wait(5000)
  stopifnot(
    !worker$is_alive(),
    length(specmill::recover_client(fault_root)) == 1L
  )
  fails(specmill::recover_client(fault_root, 'apply'), 'lock exists')
  lock <- file.path(
    normalizePath(fault_root, winslash = '/', mustWork = TRUE),
    '.specmill-lock'
  )
  stopifnot(
    !fs::is_link(lock),
    length(list.files(lock, all.files = TRUE, no.. = TRUE)) == 0L
  )
  unlink(lock, recursive = TRUE)
  specmill::recover_client(fault_root, 'apply')
  stopifnot(identical(
    unname(originals),
    unname(tools::md5sum(names(originals)))
  ))
  cat(
    'Reconciliation: six audit contracts, conservative ownership, stale edits, containment, rollback and legacy recovery passed.\n'
  )
}
if (sys.nframe() == 0L) {
  reconciliation_acceptance()
}
