# Generated by specmill; client-owned session controls.

#' Set request verbosity for this session
#' @param verbose One nonmissing logical value. Defaults to FALSE.
#' @return Invisibly NULL.
#' @details Reports the HTTP method and response status, without URLs, headers,
#'   query values, or bodies. Uses the package-scoped run_verbose R option.
#'   Does not read or write environment or profile files.
#' @export
CLIENT_PREFIX_run_verbose <- function(verbose = FALSE) {
  if (!base::is.logical(verbose) || base::length(verbose) != 1L || base::is.na(verbose)) base::stop('verbose must be TRUE or FALSE', call. = FALSE)
  base::options(base::structure(base::list(verbose), names = base::paste0(OPTION_PREFIX, '.run_verbose')))
  base::invisible(NULL)
}

#' Set dry-run mode for this session
#' @param enabled One nonmissing logical value. Defaults to FALSE.
#' @return Invisibly NULL.
#' @details In dry-run mode, endpoint functions return a prepared httr2 request
#'   without sending it. Authentication and input validation still apply.
#'   The request can contain credentials; inspect and share it with care.
#'   Uses the package-scoped dry_run R option, overriding the legacy dry-run
#'   environment flag even when FALSE. Remove the option to restore that fallback.
#'   Does not read or write environment or profile files.
#' @export
CLIENT_PREFIX_dry_run <- function(enabled = FALSE) {
  if (!base::is.logical(enabled) || base::length(enabled) != 1L || base::is.na(enabled)) base::stop('enabled must be TRUE or FALSE', call. = FALSE)
  base::options(base::structure(base::list(enabled), names = base::paste0(OPTION_PREFIX, '.dry_run')))
  base::invisible(NULL)
}
