# Generated by specmill; client-owned HTTP runtime.
api_request <- function(method, path, path_params, query, body, headers = base::list(), query_serialization = base::list(), body_media = 'application/json', auth = NULL, batch = base::list(), parameter_serialization = base::list(), cookies = base::list(), body_encoding = base::list(), form_schema = NULL, server = base::list(url = BASE_URL), request_controls = base::list()) {
  # Runtime options use the same package prefix as the dry-run environment flag.
  controls <- base::getOption(base::paste0(base::tolower(base::sub('_DRY_RUN$', '', DRY_RUN_ENV)), '.request'), base::list())
  if (!base::is.list(controls) || (base::length(controls) && (base::is.null(base::names(controls)) || base::anyNA(base::names(controls)) || base::anyDuplicated(base::names(controls)))) || base::length(base::setdiff(base::names(controls), base::c('base_url', 'timeout', 'max_retries', 'retry_writes')))) base::stop('Request controls must be a named list of base_url, timeout, max_retries, retry_writes', call. = FALSE)
  for (name in base::c('timeout', 'max_retries', 'retry_writes')) {
    if (base::is.null(controls[[name]])) controls[[name]] <- request_controls[[name]]
  }
  timeout <- if (base::is.null(controls$timeout)) 30 else controls$timeout
  retries <- if (base::is.null(controls$max_retries)) 0 else controls$max_retries
  writes <- if (base::is.null(controls$retry_writes)) FALSE else controls$retry_writes
  if (!base::is.numeric(timeout) || base::length(timeout) != 1L || !base::is.finite(timeout) || timeout <= 0) base::stop('timeout must be a finite positive number of seconds', call. = FALSE)
  if (!base::is.numeric(retries) || base::length(retries) != 1L || !base::is.finite(retries) || retries < 0 || retries != base::trunc(retries) || retries >= base::.Machine$integer.max) base::stop('max_retries must be a nonnegative integer below .Machine$integer.max', call. = FALSE)
  if (!base::is.logical(writes) || base::length(writes) != 1L || base::is.na(writes)) base::stop('retry_writes must be TRUE or FALSE', call. = FALSE)
  base_url_override <- NULL # Initialization override
  base_url <- controls$base_url
  if (base::is.null(base_url)) base_url <- base_url_override
  if (base::is.null(base_url)) {
    if (!base::is.null(server$diagnostic)) base::stop('Server selection: ', server$diagnostic, call. = FALSE)
    base_url <- server$url
  }
  valid_url <- base::is.character(base_url) && base::length(base_url) == 1L && !base::is.na(base_url) &&
    base::grepl('^https?://([A-Za-z0-9.-]+|\\[[0-9A-Fa-f:]+\\])(:[0-9]+)?(/[^?#]*)?$', base_url) &&
    !base::grepl('[[:space:]{}\\\\]', base_url) && !base::grepl('%(?![0-9A-Fa-f]{2})', base_url, perl = TRUE)
  if (valid_url) valid_url <- !base::is.null(base::tryCatch(curl::curl_parse_url(base_url), error = function(e) NULL)) &&
    !base::grepl(':0$', base::sub('^https?://([^/]+).*$', '\\1', base_url))
  if (!valid_url) base::stop('base_url must be absolute HTTP(S) without credentials, query, fragment, or unresolved variables', call. = FALSE)
  encode_parameter <- function(value, p) {
    if (base::is.null(value)) {
      if (base::isTRUE(p$required)) base::stop('Required parameter: ', p$name)
      base::return(base::character())
    }
    type <- p$schema$type
    style <- p$style
    explode <- base::isTRUE(p$explode)
    scalar <- function(x, schema) {
      valid <- !base::is.object(x) && base::is.null(base::dim(x)) && base::is.null(base::names(x)) && base::length(x) == 1L && !base::anyNA(x) &&
        (base::is.character(x) || base::is.logical(x) || (base::is.numeric(x) && base::is.finite(x)))
      if (valid && !base::is.null(schema$type)) valid <- base::switch(schema$type,
        string = base::is.character(x), boolean = base::is.logical(x),
        number = base::is.numeric(x), integer = base::is.numeric(x) && x == base::trunc(x), FALSE)
      if (!valid) base::stop('Parameter must contain finite, non-null scalars of its declared type: ', p$name)
      if (base::is.logical(x)) if (x) 'true' else 'false' else base::as.character(x)
    }
    if (base::is.object(value) || !base::is.null(base::dim(value))) base::stop('Parameter must be a plain vector or list: ', p$name)
    keys <- base::names(value)
    if (base::identical(type, 'object')) {
      if (!base::is.list(value) || (base::length(value) && base::is.null(keys)) || base::anyNA(keys) || base::anyDuplicated(keys) || base::any(!base::nzchar(keys))) base::stop('Object parameter must be a uniquely named list: ', p$name)
      if (!base::all(base::unlist(p$schema$required) %in% keys)) base::stop('Missing required parameter fields: ', p$name)
      if (base::isFALSE(p$schema$additionalProperties) && base::length(base::setdiff(keys, base::names(p$schema$properties)))) base::stop('Unknown parameter fields: ', p$name)
      values <- base::vapply(base::seq_along(value), function(i) {
        child <- p$schema$properties[[keys[[i]]]]
        if (base::is.null(child) && base::is.list(p$schema$additionalProperties)) child <- p$schema$additionalProperties
        scalar(value[[i]], child)
      }, base::character(1))
    } else if (base::identical(type, 'array')) {
      if (!base::is.null(keys) || !(base::is.atomic(value) || base::is.list(value))) base::stop('Array parameter must be an unnamed vector or list: ', p$name)
      if ((!base::is.null(p$schema$minItems) && base::length(value) < p$schema$minItems) || (!base::is.null(p$schema$maxItems) && base::length(value) > p$schema$maxItems)) base::stop('Invalid parameter array length: ', p$name)
      values <- base::vapply(value, scalar, base::character(1), schema = p$schema$items)
    } else values <- scalar(value, p$schema)
    # URI templates do not define a distinct representation for an empty list/map.
    if (type %in% base::c('array', 'object') && !base::length(values)) base::stop('Empty parameter containers cannot be encoded unambiguously: ', p$name)
    if (p$location == 'header') {
      if (base::any(base::grepl('[\r\n]', base::c(keys, values)))) base::stop('Newlines are forbidden in header parameters')
      separator <- if (base::is.null(p$collection_format)) ',' else base::switch(p$collection_format, ssv = ' ', tsv = '\t', pipes = '|', ',')
      if (type %in% base::c('array', 'object') &&
          (base::any(base::grepl(separator, base::c(keys, values), fixed = TRUE)) ||
           (type == 'object' && explode && base::any(base::grepl('=', base::c(keys, values), fixed = TRUE))))) base::stop('Header parameter values contain serialization delimiters')
      encode <- base::identity
    } else {
      separator <- if (base::identical(p$collection_format, 'tsv')) '\t' else if (style == 'spaceDelimited' || base::identical(p$collection_format, 'ssv')) ' ' else NULL
      if (!explode && !base::is.null(separator) && base::any(base::grepl(separator, base::c(keys, values), fixed = TRUE))) base::stop('Parameter values contain an ambiguous whitespace delimiter')
      encode <- function(x) utils::URLencode(base::enc2utf8(x), reserved = TRUE, repeated = TRUE)
    }
    values <- base::vapply(values, encode, base::character(1), USE.NAMES = FALSE)
    keys <- base::vapply(keys, encode, base::character(1), USE.NAMES = FALSE)
    name <- encode(p$name)
    delimiter <- if (!base::is.null(p$collection_format)) base::switch(p$collection_format, csv = ',', ssv = '%20', tsv = '%09', pipes = '|', multi = ',') else base::switch(style, spaceDelimited = '%20', pipeDelimited = '|', ',')
    if (p$location == 'header') delimiter <- if (!base::is.null(p$collection_format)) base::switch(p$collection_format, ssv = ' ', tsv = '\t', pipes = '|', ',') else ','
    flat <- if (base::identical(type, 'object')) base::as.vector(base::rbind(keys, values)) else values
    if (p$location %in% base::c('query', 'cookie')) {
      if (style == 'brackets') base::return(base::paste0(name, '%5B%5D=', values))
      if (style == 'deepObject') base::return(base::paste0(name, '[', keys, ']=', values))
      if (explode && base::identical(type, 'object')) base::return(base::paste0(keys, '=', values))
      if (explode && base::identical(type, 'array')) base::return(base::paste0(name, '=', values))
      base::return(base::paste0(name, '=', base::paste(flat, collapse = delimiter)))
    }
    if (style == 'matrix') {
      if (explode && base::identical(type, 'object')) base::return(base::paste0(';', base::paste0(keys, '=', values, collapse = ';')))
      if (explode && base::identical(type, 'array')) base::return(base::paste0(';', base::paste0(name, '=', values, collapse = ';')))
      base::return(base::paste0(';', name, if (base::length(flat) == 1L && flat == '') '' else base::paste0('=', base::paste(flat, collapse = ','))))
    }
    if (base::identical(type, 'object') && explode) flat <- base::paste0(keys, '=', values)
    if (style == 'label' && explode) {
      # Escape literal dots before adding label separators.
      flat <- base::gsub('.', '%2E', flat, fixed = TRUE)
      delimiter <- '.'
    }
    base::paste0(if (style == 'label') '.' else '', base::paste(flat, collapse = delimiter))
  }
  encoded_query <- base::list()
  encoded_cookies <- base::list()
  for (p in parameter_serialization) {
    values <- base::switch(p$location, path = path_params, query = query, header = headers, cookie = cookies)
    encoded <- encode_parameter(values[[p$name]], p)
    if (p$location == 'path') {
      path <- base::gsub(base::paste0('{', p$name, '}'), encoded, path, fixed = TRUE)
      path_params[p$name] <- NULL
    } else if (p$location == 'query') {
      encoded_query[[base::length(encoded_query) + 1L]] <- encoded
      query[p$name] <- NULL
    } else if (p$location == 'header') {
      headers[p$name] <- if (base::length(encoded)) base::list(encoded) else base::list(NULL)
    } else encoded_cookies[[base::length(encoded_cookies) + 1L]] <- encoded
  }
  for (limit in batch) {
    if (!base::is.numeric(limit) || base::length(limit) != 1L || base::is.na(limit) || !base::is.finite(limit) || limit < 1 || limit != base::floor(limit)) base::stop('Batch limits must be positive integers')
  }
  if (!base::is.null(batch$max_items) && !base::is.null(body)) {
    # Split oversized input with specmill::batched(), or directly with:
    # lapply(split(items, ceiling(seq_along(items) / size)), fn, ...)
    if (!base::is.list(body) || !base::is.null(base::names(body))) base::stop('Batch body must be an unnamed list of items')
    if (base::length(body) > batch$max_items) base::stop('Batch exceeds max_items (', batch$max_items, '); split the input into smaller requests')
  }
  for (name in base::names(path_params)) {
    path <- base::gsub(base::paste0('{', name, '}'), utils::URLencode(base::as.character(path_params[[name]]), reserved = TRUE), path, fixed = TRUE)
  }
  request <- httr2::request(base_url)
  request <- httr2::req_method(request, method)
  query <- base::Filter(base::Negate(base::is.null), query)
  for (name in base::names(query)) {
    serialization <- query_serialization[[name]]
    if (base::is.null(serialization)) serialization <- 'error'
    if (name %in% base::names(query_serialization)) {
      if (!serialization %in% base::c('comma', 'explode')) base::stop('Unsupported query array serialization')
      if (!base::is.character(query[[name]]) || base::anyNA(query[[name]])) base::stop('Query array must be a character vector without missing values')
      encoded_query[[base::length(encoded_query) + 1L]] <- encode_parameter(query[[name]], base::list(name = name, location = 'query', schema = base::list(type = 'array', items = base::list(type = 'string')), style = 'form', explode = serialization == 'explode'))
    } else request <- base::do.call(httr2::req_url_query, base::c(base::list(request, .multi = serialization), query[name]))
  }
  headers <- base::Filter(base::Negate(base::is.null), headers)
  if (base::length(headers)) request <- base::do.call(httr2::req_headers, base::c(base::list(request), headers))
  suffix <- if (base::grepl('?', request$url, fixed = TRUE)) base::sub('^[^?]*', '', request$url) else ''
  request <- httr2::req_url(request, base::paste0(base::sub('/+$', '', base_url), '/', base::sub('^/+', '', path), suffix))
  encoded_query <- base::unlist(encoded_query, use.names = FALSE)
  encoded_cookies <- base::unlist(encoded_cookies, use.names = FALSE)
  if (base::length(encoded_cookies)) {
    prior <- request$headers[['Cookie']]
    request <- httr2::req_headers(request, Cookie = base::paste(base::c(prior, encoded_cookies), collapse = '; '))
  }
  if (!base::is.null(body) && body_media %in% base::c('application/x-www-form-urlencoded', 'multipart/form-data')) {
    if (!base::is.list(body) || (base::length(body) && base::is.null(base::names(body)))) base::stop('Form body must be a named list')
    parts <- base::list()
    pairs <- base::character()
    for (name in base::names(body)) {
      field <- form_schema$properties[[name]]
      if (base::is.null(field) && base::is.list(form_schema$additionalProperties)) field <- form_schema$additionalProperties
      if (base::is.null(field$type)) base::stop('Form field needs a declared schema: ', name)
      value <- body[[name]]
      if (base::is.null(value)) base::stop('Null form fields cannot be encoded')
      enc <- body_encoding[[name]]
      if (base::is.null(enc)) enc <- base::list()
      if (body_media == 'application/x-www-form-urlencoded') {
        style <- if (base::is.null(enc$style)) 'form' else enc$style
        explode <- if (base::is.null(enc$explode)) style == 'form' else enc$explode
        if (!base::is.null(enc$collection_format)) explode <- enc$collection_format == 'multi'
        pairs <- base::c(pairs, encode_parameter(value, base::list(name = name, location = 'query', schema = field, style = style, explode = explode, collection_format = enc$collection_format)))
      } else {
        array <- base::identical(field$type, 'array')
        values <- if (array) value else base::list(value)
        if (!base::length(values)) base::stop('Empty multipart arrays cannot be encoded unambiguously')
        item <- if (array) field$items else field
        content_type <- enc$contentType
        if (base::is.null(content_type)) content_type <- if (base::identical(item$format, 'binary')) 'application/octet-stream' else if (base::identical(item$type, 'object')) 'application/json' else 'text/plain'
        scalar <- function(x) {
          if (base::is.logical(x)) { if (x) 'true' else 'false' } else base::as.character(x)
        }
        if (array && !base::is.null(enc$collection_format) && enc$collection_format != 'multi') {
          delimiter <- base::switch(enc$collection_format, csv = ',', ssv = ' ', tsv = '\t', pipes = '|')
          tokens <- base::vapply(values, scalar, base::character(1))
          if (base::any(base::grepl(delimiter, tokens, fixed = TRUE))) base::stop('Multipart values contain a serialization delimiter')
          values <- base::list(base::paste(tokens, collapse = delimiter))
        }
        for (part in values) {
          if (base::identical(item$format, 'binary')) {
            if (base::inherits(part, 'form_file')) {
              part$type <- content_type
            } else if (base::is.raw(part)) part <- curl::form_data(part, type = content_type)
            else base::stop('Binary form fields require raw or curl::form_file()')
          } else if (content_type == 'application/json') {
            part <- curl::form_data(base::as.character(jsonlite::toJSON(part, auto_unbox = TRUE, null = 'null', digits = 22)), type = content_type)
          } else part <- curl::form_data(scalar(part), type = content_type)
          parts <- base::c(parts, stats::setNames(base::list(part), name))
        }
      }
    }
    if (body_media == 'application/x-www-form-urlencoded') request <- httr2::req_body_raw(request, base::paste(pairs, collapse = '&'), type = body_media)
    else request <- base::do.call(httr2::req_body_multipart, base::c(base::list(request), parts))
  } else if (!base::is.null(body)) {
    if (!base::is.null(batch$max_bytes)) {
      bytes <- if (base::identical(body_media, 'application/json')) {
        base::charToRaw(base::enc2utf8(base::as.character(jsonlite::toJSON(body, auto_unbox = TRUE, null = 'null', digits = 22))))
      } else body
      if (!base::is.raw(bytes)) base::stop('Binary body must be a raw vector')
      if (base::length(bytes) > batch$max_bytes) base::stop('Batch exceeds max_bytes (', batch$max_bytes, ')')
      request <- httr2::req_body_raw(request, bytes, type = body_media)
    } else
    if (base::identical(body_media, 'application/octet-stream')) {
      if (!base::is.raw(body)) base::stop('Binary body must be a raw vector')
      request <- httr2::req_body_raw(request, body, type = body_media)
    } else if (base::identical(body_media, 'application/json')) {
      request <- httr2::req_body_json(request, body, auto_unbox = TRUE, null = 'null')
    } else base::stop('Unsupported request body media type')
  }
  if (!base::is.null(auth)) request <- api_auth(request, auth)
  if (base::length(encoded_cookies)) request <- httr2::req_headers(request, .redact = 'Cookie')
  # Append encoded tokens last: query authentication must not decode/re-encode them.
  if (base::length(encoded_query)) request <- httr2::req_url(request, base::paste0(request$url, if (base::grepl('?', request$url, fixed = TRUE)) '&' else '?', base::paste(encoded_query, collapse = '&')))
  request <- httr2::req_timeout(request, timeout)
  if (retries > 0 && (base::toupper(method) %in% base::c('GET', 'HEAD', 'OPTIONS', 'PUT', 'DELETE') || writes)) {
    request <- httr2::req_retry(request, max_tries = retries + 1,
      is_transient = function(response) httr2::resp_status(response) %in% base::c(408L, 429L, 500L, 502L, 503L, 504L))
  }
  if (base::tolower(base::Sys.getenv(DRY_RUN_ENV)) %in% base::c('true', '1', 'yes')) base::return(request)
  request <- httr2::req_error(request, is_error = function(response) FALSE)
  response <- base::tryCatch(httr2::req_perform(request), error = function(e) {
    base::stop('HTTP request failed before a response was received (connection, TLS, or timeout failure)', call. = FALSE)
  })
  status <- httr2::resp_status(response)
  media <- httr2::resp_header(response, 'content-type')
  if (base::is.null(media)) media <- ''
  media <- base::tolower(base::trimws(base::sub(';.*$', '', media)))
  context <- base::paste0('HTTP ', status, if (base::nzchar(media)) base::paste0(' ', media) else '')
  if (status >= 400L) base::stop(context, ' response', call. = FALSE)
  if (!httr2::resp_has_body(response)) base::return(NULL)
  bytes <- httr2::resp_body_raw(response)
  if (!base::length(bytes)) base::return(NULL)
  if (base::grepl('(/json|\\+json)$', media)) {
    decoded <- base::tryCatch(jsonlite::fromJSON(httr2::resp_body_string(response), simplifyVector = FALSE), error = base::identity)
    if (base::inherits(decoded, 'error')) base::stop('Cannot decode ', context, ' response as JSON', call. = FALSE)
    base::return(decoded)
  }
  if (base::startsWith(media, 'text/') || media == 'image/svg+xml') base::return(httr2::resp_body_string(response))
  bytes
}
