initialize_client <- function(
  root,
  schema,
  package = NULL,
  title = NULL,
  author = NULL,
  license = NULL,
  base_url = NULL,
  naming = c('operation_id', 'tag_prefix'),
  group_by = c('tag', 'none')
) {
  if (is.data.frame(schema)) {
    return(initialize_apis(
      root,
      schema,
      package,
      title,
      author,
      license,
      match.arg(naming),
      match.arg(group_by)
    ))
  }
  schema <- normalizePath(schema, winslash = '/', mustWork = TRUE)
  naming <- match.arg(naming)
  group_by <- match.arg(group_by)
  document <- read_schema_document(schema)
  if (is.null(base_url) && length(document$servers)) {
    base_url <- document$servers[[1L]]$url
  }
  config_string(base_url, 'base_url')
  if (!grepl('^https?://[^/]+', base_url)) {
    stop(
      'Supply an absolute HTTP base_url; relative servers need a recorded origin'
    )
  }
  description <- file.path(root, 'DESCRIPTION')
  existing <- file.exists(description)
  if (existing) {
    metadata <- read.dcf(description)[1L, ]
    if (
      !is.null(package) && !identical(package, unname(metadata[['Package']]))
    ) {
      stop('Package metadata conflicts with DESCRIPTION')
    }
    package <- unname(metadata[['Package']])
  } else {
    config_string(package, 'package')
    config_string(title, 'title')
    config_string(license, 'license')
    config_fields(author, c('given', 'family', 'email'), 'author')
    for (field in c('given', 'family', 'email')) {
      config_string(author[[field]], paste('author', field))
    }
    metadata <- c(
      Package = package,
      Title = title,
      Version = '0.0.0.9000',
      'Authors@R' = paste0(
        'person(',
        r_literal(author$given),
        ', ',
        r_literal(author$family),
        ', email = ',
        r_literal(author$email),
        ", role = c('aut', 'cre'))"
      ),
      Description = paste(title, 'Client generated from a local API schema.'),
      License = license,
      Encoding = 'UTF-8',
      Imports = 'httr2, jsonlite, curl',
      Suggests = 'testthat'
    )
  }
  if (!grepl('^[A-Za-z][A-Za-z0-9.]*$', package) || endsWith(package, '.')) {
    stop('Invalid R package name')
  }
  imports <- trimws(sub(
    ' *\\(.*',
    '',
    strsplit(
      metadata[['Imports']] %or% '',
      ',',
      fixed = TRUE
    )[[1L]]
  ))
  needs_helper <- !file.exists(file.path(root, 'R', 'api_request.R'))
  if (existing && !all(c('httr2', 'jsonlite') %in% imports)) {
    stop(
      'Existing DESCRIPTION must declare httr2 and jsonlite before adding the default transport'
    )
  }
  if (existing && needs_helper && !'curl' %in% imports) {
    stop(
      'Existing DESCRIPTION must declare curl before adding the default transport'
    )
  }
  helper <- readLines(
    system.file('templates/request.R', package = 'specmill', mustWork = TRUE),
    warn = FALSE
  )
  helper <- gsub('BASE_URL', r_literal(base_url), helper, fixed = TRUE)
  proposal <- configuration_proposal(schema, package, naming, group_by)
  if (
    any(vapply(
      proposal$diagnostics,
      function(x) x$code == 'group_collision',
      logical(1)
    ))
  ) {
    stop('Tag groups collide; inspect configure_client() before initialization')
  }
  output <- c(
    proposal$files,
    list(
      'R/api_request.R' = paste(helper, collapse = '\n'),
      '.Rbuildignore' = '^specmill\\.yml$\n^apis$\n^schema$\n^\\.specmill$'
    )
  )
  if (!existing) {
    dcf <- character()
    connection <- textConnection('dcf', 'w', local = TRUE)
    write.dcf(as.list(metadata), connection)
    close(connection)
    output[['DESCRIPTION']] <- paste(dcf, collapse = '\n')
    output[['NAMESPACE']] <- '# Generated by roxygen2: do not edit by hand'
    if (license == 'MIT + file LICENSE') {
      output[['LICENSE']] <- paste0(
        'YEAR: ',
        format(Sys.Date(), '%Y'),
        '\nCOPYRIGHT HOLDER: ',
        author$given,
        ' ',
        author$family
      )
    }
  }
  conflicts <- names(output)[file.exists(file.path(root, names(output)))]
  if (length(conflicts)) {
    stop(
      'Initialization conflicts with existing files: ',
      paste(conflicts, collapse = ', ')
    )
  }
  if (!dir.exists(root) && !dir.create(root, recursive = TRUE)) {
    stop('Cannot create client root')
  }
  result <- apply_files(root, output, mode = 'apply')
  attr(result, 'configuration') <- proposal
  result
}
