name: Commit Lint

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: commit-lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  commit-lint:
    name: Commit Lint
    uses: seanthimons/baseline/.github/workflows/commit-lint.yaml@0a2a80a6d045ffbdacedd59e35dce1497e2acfc1 # v1.0.0
