name: Commit Lint

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: commit-lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  commit-lint:
    name: Commit Lint
    uses: seanthimons/baseline/.github/workflows/commit-lint.yaml@c99a0a60eed152a08d1e34841d45573fef812af2 # v1.2.0
