name: Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "43 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    uses: seanthimons/baseline/.github/workflows/gitleaks.yaml@c99a0a60eed152a08d1e34841d45573fef812af2 # v1.2.0
