name: Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "43 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    uses: seanthimons/baseline/.github/workflows/gitleaks.yaml@0a2a80a6d045ffbdacedd59e35dce1497e2acfc1 # v1.0.0
