name: Lint workflows

on:
  push:
    paths: ['.github/**']
  pull_request:
    paths: ['.github/**']

permissions:
  contents: read

concurrency:
  group: lint-workflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint workflows
    uses: seanthimons/baseline/.github/workflows/lint-workflows.yaml@0a2a80a6d045ffbdacedd59e35dce1497e2acfc1 # v1.0.0
